theme: jekyll-theme-minimal
title: Visualizing the University of Victoria in Wikidata
description: The goal of this project is to experiment with using Wikidata to increase the presence and discoverability of the University of Victoria (UVic) and support the creation of scholarly profiles.
